# Generated by Django 4.2.5 on 2023-09-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_urinestrip_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urinestrip',
            name='colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
